name: ci

on:
  push:
    branches:
      - "**" # every branch
  workflow_dispath: # to be able to run workflow manually from GitHub actions 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout to repo
        uses: actions/checkout@v2

      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: lintint
        run: pip install nox